'''
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''


from random import randint

def compare_guess(guess, goal):
    cow = 0
    bull = 0
    for i in range(0, 4):
        if guess[i] == goal[i]:
            cow += 1
        elif guess[i] in goal:
            bull += 1
    print("%d cow"%cow, "%d bull"%bull)
    return cow == 4

def main():
    print("【* Welcome to Cows and Bulls Game *】")
    play = True

    while play:
        goal = randint(1000, 9999)
        result = False
        count = 0
#        print(goal)
        while not result:
            guess = input("Enter your guess number: ").lower()
            if guess == 'q':
                play = False
                break
            elif not guess.isdigit() or  len(guess) != 4:
                print("Invalid enter, please enter a 4-digit number")
                continue
            else:
                result = compare_guess(guess, str(goal))
                count += 1
            if result:
                print("Your total guesses is %d"%count)
                play = input("【'C'/Continue | 'Q'/Quit】").lower() == 'c'
                break

if __name__ == '__main__':
    main()
